#!/bin/bash

# based on: https://github.com/thedatasociety/lab-neo4j/blob/master/binder/postBuild
###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Building everything up
echo "Building everything up (jupyter lab build)"
jupyter lab build 

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#             neo4j installation commands                   #
###############################################################

export NEO4J_VERSION=3.5.14
echo "export NEO4J_VERSION=${NEO4J_VERSION}" >> ~/.bashrc
echo "export NEO4J_VERSION=${NEO4J_VERSION}" >> ~/.profile

export NEO4J_HOME=$(pwd)/neo4j-community-${NEO4J_VERSION}
echo "export NEO4J_HOME=${NEO4J_HOME}"       >> ~/.bashrc
echo "export NEO4J_HOME=${NEO4J_HOME}"       >> ~/.profile


wget http://dist.neo4j.org/neo4j-community-${NEO4J_VERSION}-unix.tar.gz -q
tar -xvf neo4j-community-${NEO4J_VERSION}-unix.tar.gz
rm neo4j-community-${NEO4J_VERSION}-unix.tar.gz

# This should allow the db to listen if it does...
# Comment it out if you'd rather be a bit more secure
echo "dbms.connectors.default_listen_address=0.0.0.0" >> ${NEO4J_HOME}/conf/neo4j.conf

# neo4j has a default password: neo4j
# However, if you log in with that, the session will soon time out
# and you will be required to update the original default password 
${NEO4J_HOME}/bin/neo4j-admin set-initial-password neo
mkdir -p ${NEO4J_HOME}/data/databases/graph.db
${NEO4J_HOME}/bin/neo4j-admin load --from=neo4j/shopizer-2.12.0.dump --force

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$NEO4J_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$NEO4J_HOME/bin"  >> ~/.profile

source ~/.bashrc