#!/bin/bash

if [ ! -f neo4j-community-3.5.14-unix.tar.gz ]; then
  wget http://dist.neo4j.org/neo4j-community-3.5.14-unix.tar.gz
fi

tar -xvf neo4j-community-3.5.14-unix.tar.gz

# This should allow the db to listen if it does...
# Comment it out if you'd rather be a bit more secure
echo "dbms.connectors.default_listen_address=0.0.0.0" >> neo4j-community-3.5.14/conf/neo4j.conf

# neo4j has a default password: neo4j
# However, if you log in with that, the session will soon time out
# and you will be required to update the original default password 
neo4j-community-3.5.14/bin/neo4j-admin set-initial-password neo
mkdir -p neo4j-community-3.5.14/data/databases/graph.db
neo4j-community-3.5.14/bin/neo4j-admin load --from=neo4j/shopizer-2.12.0.dump --force

# enable dashboard extension
jupyter nbextension install --py jupyter_dashboards --sys-prefix
jupyter nbextension enable --py jupyter_dashboards --sys-prefix